### ISSUE TITLE
Try out CAN SDK login mechanims

### ISSUE THREAD

**Issue by tvierro2** [Freshmen/freshman-orienteering#4]
Use the CAN SDK to direct the user to facebook login, display users name on the page once he has logged in

**Comment by Vidhuran** [comment]
The login example doesn't work from the Amazon Instance. IN login.js there is a function to get some URL and that returns the localhost URL rather than the ec2's URL. 
And i screwed up the permissions for the examples directory, so for now delete the Dev.js file if it already exists and then just run test.sh (it should pick up the API key by itself 
)

**Comment by tvierro2** [comment]
We investigated the problem with Ken and apparently the f-secure login mechanism needs the redirect url to be somehow white-listed. Therefore, the redirection in the example configuration only workson the same host where the node server runs (pages are served from 127.0.0.1).
If we change the redirect url in index.js from http://127.0.0.1/login.html to http://{any other host}/login.hmtl then the f-secure site stops redirecting and serves just a 404 error. 

This is the redirect mechanism: 
https://oneid-fip.sp.f-secure.com/OneID/sso/2_0_0/oauth2/login/fip-fb?app_id=900bro&operator_key=699&redirect_url=http://127.0.0.1/login.html [WORKS -> Redirects, but the page cannot be server from localhost]

https://oneid-fip.sp.f-secure.com/OneID/sso/2_0_0/oauth2/login/fip-fb?app_id=900bro&operator_key=699&redirect_url=http://www.aalto.fi/ [DOEN't WORK] aalto.fi is just an example
